test_that("OU temporal-kernel recovery runner freezes a direct DGP and refuses overwrite", {
  root <- .temporal_program_repo_root()
  skip_if(is.null(root), "temporal programme files are unavailable in an installed check")
  script <- file.path(root, "dev", "temporal-program", "run-ou-kernel-recovery.R")
  contract <- file.path(root, "dev", "temporal-program", "TEMPORAL-OU-KERNEL-RECOVERY-CONTRACT.md")
  expect_true(file.exists(script))
  expect_true(file.exists(contract))
  source_text <- paste(readLines(script, warn = FALSE), collapse = "\n")
  contract_text <- paste(readLines(contract, warn = FALSE), collapse = "\n")
  expect_false(grepl("simulate\\.gllvmTMB", source_text))
  expect_match(source_text, "OU_KERNEL_RECOVERY_OUTPUT")
  expect_match(source_text, "OU_KERNEL_RECOVERY_PLAN_INDEX")
  expect_match(source_text, "output must name a new directory")
  expect_match(source_text, "c\\(\\.25, \\.70, 1\\.40\\)")
  expect_match(source_text, "2609371:2609373")
  expect_match(contract_text, "absolute log-rate error")
  expect_match(contract_text, "not a general decay-rate recovery")
})
