d102_methods <- c(QD=0L,QF=1L,JD=2L,JF=3L)
d102_gh <- function(n=31L) { j<-seq_len(n-1L); J<-matrix(0,n,n); J[cbind(j,j+1L)]<-J[cbind(j+1L,j)]<-sqrt(j/2); e<-eigen(J,symmetric=TRUE); x<-e$values; h0<-rep(1,n); h1<-2*x; if(n>2) for(k in 2:(n-1L)){h2<-2*x*h1-2*(k-1)*h0;h0<-h1;h1<-h2}; w<-exp((n-1)*log(2)+lgamma(n+1)-2*log(n)-2*log(abs(h1))); list(z=sqrt(2)*x,w=w/sum(w)) }
d102_softplus <- function(x) pmax(x,0)+log1p(exp(-abs(x)))
d102_loading <- function(x,T=6L) { L<-matrix(0,T,2);L[1,1]<-exp(x[1]);L[2,]<-c(x[2],exp(x[3]));L[3:T,]<-matrix(x[4:length(x)],T-2,2,byrow=TRUE);L }
d102_loading_free <- function(L) c(log(L[1,1]),L[2,1],log(L[2,2]),as.vector(t(L[3:nrow(L),,drop=FALSE])))
d102_logsumexp <- function(x) { a<-max(x);a+log(sum(exp(x-a))) }
d102_marginal <- function(y,beta,lf,gh=d102_gh(61L)) { L<-d102_loading(lf,ncol(y));lw<-log(gh$w);ans<-0;for(i in seq_len(nrow(y))){z<-numeric(length(gh$z)^2);k<-0L;for(a in seq_along(gh$z))for(b in seq_along(gh$z)){k<-k+1L;e<-beta+L[,1]*gh$z[a]+L[,2]*gh$z[b];z[k]<-lw[a]+lw[b]+sum(y[i,]*e-d102_softplus(e))};ans<-ans+d102_logsumexp(z)};ans }
d102_prob <- function(beta,lf,gh=d102_gh(61L)) { L<-d102_loading(lf,length(beta));w<-outer(gh$w,gh$w);vapply(seq_along(beta),function(t)sum(w*outer(gh$z,gh$z,function(a,b)plogis(beta[t]+L[t,1]*a+L[t,2]*b))),0.0) }
d102_pack <- function(beta,lf,m,ch) c(beta,lf,as.vector(m),as.vector(ch))
d102_unpack <- function(x,n,T,full) { g<-3*T-1L; me<-g+2*n;cc<-if(full)3L else 2L;list(beta=x[seq_len(T)],lf=x[(T+1):g],mean=matrix(x[(g+1):me],n,2),chol=matrix(x[(me+1):(me+cc*n)],n,cc)) }
d102_starts <- function(y,L,beta) { emp<-qlogis(pmin(.95,pmax(.05,colMeans(y)))); list(A=list(beta=emp,lf=c(log(.4),0,log(.4),rep(0,8))),B=list(beta=beta+c(.05,-.04,.03,-.02,.01,-.05),lf=d102_loading_free(.9*L)),C=list(beta=emp+c(.15,-.1,.05,.1,-.05,-.15),lf=c(log(.65),.1,log(.6),c(.1,-.1,-.1,.1,.15,-.1,-.1,-.15)))) }
d102_fixture <- function(seed,n,regime) { beta<-c(-.6,-.2,.18,.45,-.36,.08);L<-if(regime=="near_diag")rbind(c(.78,0),c(.05,.66),c(-.12,.10),c(.18,-.08),c(-.10,-.13),c(.12,.14)) else rbind(c(.78,0),c(.32,.66),c(-.44,.45),c(.52,-.35),c(-.35,-.50),c(.38,.48)); set.seed(seed);u<-matrix(rnorm(n*2),n,2);p<-plogis(sweep(u%*%t(L),2,beta,"+"));y<-matrix(rbinom(n*6,1,as.vector(p)),n,6);if(any(colSums(y)%in%c(0,n)))stop("degenerate response");list(y=y,beta=beta,L=L,prob=d102_prob(beta,d102_loading_free(L))) }
d102_compile <- local({ dll<-NULL;function(src){if(!is.null(dll))return(dll);d<-tempfile("d102-");dir.create(d);file.copy(src,file.path(d,"design102_variational.cpp"));old<-setwd(d);on.exit(setwd(old));TMB::compile("design102_variational.cpp",flags="-O0");dll<<-list(stem="design102_variational",path=normalizePath(TMB::dynlib("design102_variational")));dyn.load(dll$path);dll}})
d102_fit <- function(f,method,start,src) { full<-method%in%c("QF","JF"); ch<-if(full)cbind(rep(log(.8),nrow(f$y)),0,rep(log(.8),nrow(f$y)))else cbind(rep(log(.8),nrow(f$y)),rep(log(.8),nrow(f$y))); o<-TMB::MakeADFun(data=list(y=f$y,method_id=d102_methods[[method]],gh_nodes=d102_gh(31)$z,gh_weights=d102_gh(31)$w),parameters=list(beta=start$beta,loading_free=start$lf,mean=matrix(0,nrow(f$y),2),chol_free=ch),DLL=d102_compile(src)$stem,silent=TRUE);x<-d102_pack(start$beta,start$lf,matrix(0,nrow(f$y),2),ch);p1<-nlminb(x,o$fn,o$gr,control=list(iter.max=180,eval.max=260));p2<-optim(p1$par,o$fn,o$gr,method="BFGS",control=list(maxit=280,reltol=1e-10));z<-d102_unpack(p2$par,nrow(f$y),6,full);g<-max(abs(o$gr(p2$par)));ok<-p2$convergence==0&&is.finite(g)&&g<1e-3&&all(is.finite(p2$par));list(status=if(ok)"healthy"else"unhealthy",code=p2$convergence,gradient_max=g,objective=-p2$value,beta=z$beta,lf=z$lf,common=d102_marginal(f$y,z$beta,z$lf),beta_rmse=sqrt(mean((z$beta-f$beta)^2)),sigma_rel=sqrt(sum((tcrossprod(d102_loading(z$lf))-tcrossprod(f$L))^2))/sqrt(sum(tcrossprod(f$L)^2)),prob_rmse=sqrt(mean((d102_prob(z$beta,z$lf)-f$prob)^2))) }
