test_that("G2k calibration contract freezes a pre-screened 150-seed all-attempt grid", {
  runner <- test_path("..", "..", "dev", "isdm-package-recovery", "run-g2k-calibration.R")
  text <- paste(readLines(runner, warn = FALSE), collapse = "\n")
  screen <- test_path("..", "..", "dev", "isdm-package-recovery", "g2l-eligible-seeds.R")
  expect_true(file.exists(screen))
  expect_match(text, "g2l_screen_eligible_seeds")
  expect_match(paste(readLines(screen, warn = FALSE), collapse = "\n"), "86201L:87000L")
  expect_match(text, "n_requested = length\\(seeds\\)")
  expect_match(text, "n_missing")
  expect_match(text, "No fit was run")
})
