test_that("S4 public phylo_dep receipt runner is present", {
  expect_true(file.exists(testthat::test_path("run-destination-b-s4-public-phylo-dep-isolated.R")))
})

test_that("S4 public phylo_dep receipt runner uses ASCII Julia string literals", {
  environment <- new.env(parent = baseenv())
  withr::local_envvar(GLLVM_S4_PUBLIC_PHYLO_DEP_DEFINE_ONLY = "1")
  withr::local_options(useFancyQuotes = TRUE)
  source(testthat::test_path("run-destination-b-s4-public-phylo-dep-isolated.R"), local = environment)
  literal <- environment$s4_public_phylo_dep_julia_literal(tempdir())
  expect_identical(literal, paste0('"', normalizePath(tempdir()), '"'))
  expect_false(grepl("[\u201c\u201d]", literal))
})

test_that("S4 public phylo_dep receipt refuses malformed endpoints and duplicate output", {
  environment <- new.env(parent = baseenv())
  withr::local_envvar(GLLVM_S4_PUBLIC_PHYLO_DEP_DEFINE_ONLY = "1")
  source(testthat::test_path("run-destination-b-s4-public-phylo-dep-isolated.R"), local = environment)
  targets <- environment$s4_public_phylo_dep_targets()
  payload <- list(target_names = targets, native_lower = seq_along(targets), native_upper = seq_along(targets) + 1, julia_lower = seq_along(targets), julia_upper = seq_along(targets) + 1)
  expect_identical(environment$s4_public_phylo_dep_validate_endpoints(payload)$target_names, targets)
  payload$target_names[7] <- "wrong"
  expect_error(environment$s4_public_phylo_dep_validate_endpoints(payload), "target/order mismatch")
  expect_error(environment$s4_public_phylo_dep_validate_endpoints(list(target_names = targets)), "dangling endpoint output")
  ordered <- list(target_names = targets, native_lower = seq_along(targets), native_upper = seq_along(targets) + 1, julia_lower = seq_along(targets), julia_upper = seq_along(targets) + 1)
  ordered$native_upper[1] <- ordered$native_lower[1]
  ordered$julia_upper[1] <- ordered$julia_lower[1]
  expect_error(environment$s4_public_phylo_dep_validate_endpoints(ordered), "ordered endpoints")
  expect_true(is.function(environment$s4_public_phylo_dep_validate_frozen_manifest))
  expect_identical(environment$s4_public_phylo_dep_known_manifest_sha256(), "1c4844db1a58c6b978494668cbf9b9e789792103a15cbf52e866a87836090b57")
  expect_true(is.function(environment$s4_public_phylo_dep_validate_embedded_julia_runtime))
  forged <- list(kind = "destination_b_frozen_r_binary_build", frozen_reference_commit = "b4d5fee64def88bc768dda1f1f77c29b295edd86", source_archive_sha256 = "0c2f4323eb9fb19acccf039b8d57b4dd6bda82e2aa8b4a7bb712f36a64b022bc", shared_object_sha256 = paste(rep("0", 64), collapse = ""))
  expect_error(environment$s4_public_phylo_dep_validate_frozen_manifest(forged, "."), "known source archive and DLL")
  copied_manifest <- tempfile(fileext = ".json")
  withr::defer(unlink(copied_manifest))
  manifest_source <- testthat::test_path("..", "..", "docs", "dev-log", "artifacts", "2026-09-09-destination-b-frozen-r-binary-build-manifest.json")
  writeLines(c(readLines(manifest_source), ""), copied_manifest)
  valid_manifest <- jsonlite::read_json(copied_manifest, simplifyVector = TRUE)
  expect_error(environment$s4_public_phylo_dep_validate_frozen_manifest(valid_manifest, ".", copied_manifest), "manifest bytes")
  malformed <- list(target_names = targets, native_lower = seq_along(targets), native_upper = seq_along(targets) + 1, julia_lower = seq_along(targets), julia_upper = seq_along(targets) + 1)
  malformed$target_names[2] <- malformed$target_names[1]
  expect_error(environment$s4_public_phylo_dep_validate_endpoints(malformed), "target/order mismatch")
  malformed <- list(target_names = targets, native_lower = seq_along(targets)[-1], native_upper = seq_along(targets) + 1, julia_lower = seq_along(targets), julia_upper = seq_along(targets) + 1)
  expect_error(environment$s4_public_phylo_dep_validate_endpoints(malformed), "target/order mismatch")
  malformed <- list(target_names = targets, native_lower = c(NA_real_, 2:7), native_upper = seq_along(targets) + 1, julia_lower = seq_along(targets), julia_upper = seq_along(targets) + 1)
  expect_error(environment$s4_public_phylo_dep_validate_endpoints(malformed), "target/order mismatch")
  malformed <- list(target_names = targets, native_lower = seq_along(targets), native_upper = seq_along(targets) + 1, julia_lower = seq_along(targets) + 1, julia_upper = seq_along(targets) + 2)
  expect_error(environment$s4_public_phylo_dep_validate_endpoints(malformed), "tolerance exceeded")
  path <- tempfile(fileext = ".json")
  withr::defer(unlink(path))
  expect_identical(environment$s4_public_phylo_dep_write_once(list(ok = TRUE), path), path)
  expect_error(environment$s4_public_phylo_dep_write_once(list(ok = FALSE), path), "refusing to overwrite")
  cat("S4_PUBLIC_PHYLO_DEP_RUNNER_CONTRACT_PASS\n")
})
