args <- commandArgs(trailingOnly = TRUE)
stopifnot(length(args) == 1L, file.exists(args))
script_path <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE))
root <- normalizePath(file.path(dirname(script_path), "..", ".."))
source(file.path(root, "dev", "pvt02", "pvt02-contract.R"))
rows <- utils::read.csv(args[[1L]], stringsAsFactors = FALSE)
expected <- pvt02_seed_window(50001L, 2L)
pvt02_validate_attempt_rows(rows, expected)
stopifnot(all(rows$family == "gaussian"), all(rows$tier == "unit"))
stopifnot(all(rows$mode == "latent"), all(rows$unique))
stopifnot(all(rows$d == 2L), all(rows$n_units == 400L), all(rows$trait == 1L))
stopifnot(all(rows$profile_scale == "log_V"), all(rows$level == 0.95))
stopifnot(all(is.finite(rows$runtime_s)), any(rows$eligible), any(!rows$ci_failed))
cat("PVT02_SMOKE_RECEIPT_PASS\n")
