args <- commandArgs(trailingOnly = TRUE); if (length(args) != 2L) stop("usage: verify-pilot.R <pilot-plan.rds> <output-dir>", call. = FALSE)
source("dev/isdm-requalification/response-information/contract.R", local = TRUE); source("dev/isdm-requalification/response-information/records.R", local = TRUE); source("dev/isdm-requalification/response-information/recompute.R", local = TRUE)
plan <- readRDS(args[[1L]]); records <- isdm_respinfo_pilot_dispositions(plan, args[[2L]])
ok <- vapply(records, function(x) identical(x$status, "fit_returned") && identical(x$disposition_source, "worker") && isTRUE(x$optimizer_entered) && identical(as.integer(x$diagnostics$convergence), 0L) && isTRUE(x$diagnostics$pd_hessian) && isTRUE(x$diagnostics$finite) && is.finite(x$diagnostics$max_gradient) && x$diagnostics$max_gradient <= ISDM_RESPINFO_GRADIENT_MAX && !is.null(x$raw) && all(is.finite(unlist(isdm_respinfo_recompute_raw(x$raw), use.names = FALSE))) && is.finite(x$diagnostics$peak_rss_bytes) && x$diagnostics$peak_rss_bytes <= 8 * 1024^3, logical(1L))
if (length(records) != 16L || !all(ok)) stop("retained pilot gate failed", call. = FALSE)
if (length(unique(vapply(records, `[[`, character(1L), "source_sha"))) != 1L || length(unique(vapply(records, `[[`, character(1L), "harness_manifest_sha256"))) != 1L) stop("retained pilot is not hash-bound to one runtime", call. = FALSE)
pairs <- split(records, vapply(records, function(x) as.integer(x$task$dataset_id), integer(1L)))
if (!all(vapply(pairs, function(pair) length(pair) == 2L && identical(pair[[1L]]$raw$baseline_data_sha256, pair[[2L]]$raw$baseline_data_sha256), logical(1L)))) stop("retained pilot baseline nesting receipt failed", call. = FALSE)
cat("response information pilot verification passed\n")
