#!/usr/bin/env Rscript
args<-commandArgs(trailingOnly=TRUE); val<-function(n,d=NULL){x<-grep(paste0("^--",n,"="),args,value=TRUE);if(!length(x))d else sub(paste0("^--",n,"="),"",x[[1]])}
mode<-val("mode","validate");root<-val("output",NULL);pkg<-normalizePath(val("pkg",getwd()),mustWork=TRUE);sha<-val("campaign-sha",NULL)
if(!mode%in%c("validate","smoke")||is.null(root))stop("require validate/smoke and output",call.=FALSE)
root<-normalizePath(if(grepl("^/",root))root else file.path(getwd(),root),mustWork=FALSE);script<-normalizePath(sub("^--file=","",grep("^--file=",commandArgs(FALSE),value=TRUE)[[1]]),mustWork=TRUE);base<-dirname(script)
source(file.path(base,"g2h-360cell-fixture.R"),local=TRUE);hash<-function(x)unname(tools::md5sum(x))[[1L]];commit<-function()system2("git",c("-C",pkg,"rev-parse","HEAD"),stdout=TRUE)[[1]]
check<-function(){fx<-g2h_make_fixture();g2h_validate_fixture(fx);fx}
if(mode=="validate"){check();cat("G2H smoke wrapper validation PASS (no fit)\n");quit(save="no")}
parent<-normalizePath(file.path(pkg,"dev","isdm-package-recovery","results"),mustWork=FALSE);if(!startsWith(root,paste0(parent,"/"))||dir.exists(root)&&length(list.files(root,all.files=TRUE,no..=TRUE))||is.null(sha)||!identical(sha,commit()))stop("fresh root and current campaign-sha required",call.=FALSE)
dir.create(root,recursive=TRUE);fx<-check();rec<-list(kind="G2H_SMOKE",commit=commit(),seed=g2h_seed,runner_md5=hash(script),fixture_md5=hash(file.path(base,"g2h-360cell-fixture.R")),protocol_md5=hash(file.path(base,"2026-08-11-g2h-360cell-protocol.md")),decision_md5=hash(file.path(base,"2026-08-11-g2h-360cell-decision.md")));saveRDS(rec,file.path(root,"root-receipt.rds"));saveRDS(fx$truth,file.path(root,"truth.rds"));stage<-function(x)write(x,file=file.path(root,"stage.txt"),append=TRUE)
stage("fixture_validated");suppressMessages(devtools::load_all(pkg,quiet=TRUE));stage("optimizer_entered");set.seed(g2h_seed+100000L)
fit<-tryCatch(.gll_isdm_fit(fx$rows,fx$X,fx$B,d=1L,control=gllvmTMBcontrol(n_init=3L,init_jitter=.25,se=TRUE,aghq=FALSE,warn_runaway=TRUE),silent=TRUE),error=function(e)e);stage("optimizer_returned")
if(inherits(fit,"error")){saveRDS(list(reason="fit_error",detail=conditionMessage(fit)),file.path(root,"profile-ledger.rds"));saveRDS(list(classification=NA,diagnostic_state="INVALID_FIT_ERROR"),file.path(root,"decision-ledger.rds"));status<-"G2H_SMOKE_HOLD"}else{saveRDS(fit,file.path(root,"fit.rds"));stage("fit_retained");profiles<-lapply(1:6,function(k){basep<-fit$tmb_obj$env$parList(fit$opt$par)$theta_diag_B;offs<-c(-2,-1,0,1,2);do.call(rbind,lapply(offs,function(o){p<-fit$tmb_obj$env$parList(fit$opt$par);p$theta_diag_B[k]<-basep[k]+o;m<-fit$tmb_map;s<-factor(seq_along(basep));s[k]<-NA;m$theta_diag_B<-s;ob<-TMB::MakeADFun(data=fit$tmb_data,parameters=p,map=m,random=fit$random,DLL=fit$tmb_obj$env$DLL,silent=TRUE);op<-tryCatch(nlminb(ob$par,ob$fn,ob$gr),error=function(e)e);data.frame(offset=o,nll=if(inherits(op,"error"))NA else ob$fn(op$par),convergence=if(inherits(op,"error"))NA else op$convergence)}))});names(profiles)<-paste0("sp",1:6);for(k in 1:6)profiles[[k]]$delta_nll<-profiles[[k]]$nll-profiles[[k]]$nll[profiles[[k]]$offset==0];valid<-vapply(profiles,function(x)all(is.finite(x$nll))&&all(x$convergence==0),logical(1));fixed<-.gllvmTMB_b_fix_values(fit);gh<-vapply(paste0("sp",1:6),function(sp){i<-grep(paste0("trait",sp,".*isdm_gbif_b_bias"),fit$X_fix_names);if(length(i)==1)fixed[i]else NA_real_},numeric(1));ge<-max(abs(gh-fx$truth$constants$gamma));lower<-vapply(profiles,function(x)x$delta_nll[x$offset==-2],numeric(1));gr<-max(abs(fit$tmb_obj$gr(fit$opt$par)));class<-if(!all(valid)||!is.finite(ge))NA_character_ else if(sum(lower>=2)>=2&&ge<.30)"GEOMETRY_RESPONSIVE" else if(ge<.30)"PROFILE_LIMITED" else "NONRESPONSIVE";saveRDS(profiles,file.path(root,"profile-ledger.rds"));saveRDS(list(classification=class,gamma_error=ge,lower_delta_nll=lower,profile_valid=valid,max_gradient=gr,three_restarts=nrow(fit$restart_history)==3),file.path(root,"decision-ledger.rds"));status<-if(all(valid)&&nrow(fit$restart_history)==3&&gr<=1e-3)"G2H_SMOKE_COMPLETE" else "G2H_SMOKE_HOLD"}
stage("artifacts_written");fs<-list.files(root,full.names=TRUE);utils::write.csv(data.frame(path=basename(fs),md5=vapply(fs,hash,character(1))),file.path(root,"file-manifest.csv"),row.names=FALSE);writeLines(c(paste0("# ",status),if(exists("class")&&!is.na(class))paste0("classification: ",class)else "classification: none"),file.path(root,"smoke-receipt.md"));cat(if(exists("class")&&!is.na(class))class else status,"\n")
