#!/usr/bin/env Rscript
# Reconcile gllvmTMB's public capability ledger (docs/design/capability-status.md,
# generated by dev/gapclose/build-capability-status.R from the validation-debt
# register) against GLLVM.jl's own docs/design/capability-status.md, at a named
# git ref. Mirrors DRM.jl's tools/parity_ledger.py precedent: matched rows,
# an "AHEAD OF gllvmTMB, ACCOUNTED FOR IN WRITING" section for every
# Julia-only row (port / accounted / divergence disposition), the symmetric
# "AHEAD OF GLLVM.jl" R-only list, and a closing CLOSURE: PASS / FAIL line.
#
# Usage:
#   Rscript tools/parity_ledger.R
#   Rscript tools/parity_ledger.R --ref origin/main
#   Rscript tools/parity_ledger.R --julia-repo "/path/to/GLLVM.jl" --ref origin/main
#   Rscript tools/parity_ledger.R --julia /path/to/a/capability-status.md   # read a file directly
#   Rscript tools/parity_ledger.R --check-names                            # near-miss / grouping-level assertions
#
# Julia source resolution (no --julia given): `git -C <julia-repo> show
# <ref>:docs/design/capability-status.md`, where <julia-repo> defaults to
# /Users/z3437171/Dropbox/Github Local/GLLVM.jl and <ref> defaults to
# origin/main; if that git call fails (repo absent, ref absent, git error),
# fall back to the scratchpad copy so the tool still runs.

args <- commandArgs(trailingOnly = TRUE)
get_flag <- function(flag, default = NULL) {
  i <- which(args == flag)
  if (length(i) == 0) return(default)
  if (i == length(args)) stop(flag, " needs a value")
  args[i + 1]
}
CHECK_NAMES <- "--check-names" %in% args

this_file <- sub("^--file=", "", grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE))
if (length(this_file) == 0) this_file <- "tools/parity_ledger.R"
ROOT <- normalizePath(file.path(dirname(this_file), ".."), mustWork = TRUE)

R_LEDGER_PATH <- file.path(ROOT, "docs", "design", "capability-status.md")

JULIA_REPO_DEFAULT <- "/Users/z3437171/Dropbox/Github Local/GLLVM.jl"
SCRATCHPAD_FALLBACK <- "/private/tmp/claude-503/-Users-z3437171-Dropbox-Github-Local-gllvmTMB/46df980d-b0f8-4444-a181-ed4b4a683bbe/scratchpad/gllvmjl-capability-status-main.md"

julia_path_arg <- get_flag("--julia")
julia_repo <- get_flag("--julia-repo", JULIA_REPO_DEFAULT)
ref <- get_flag("--ref", "origin/main")

# ---------------------------------------------------------------------------
# 1. Load the Julia ledger's raw text.
# ---------------------------------------------------------------------------

julia_source_desc <- NULL
julia_text <- NULL

if (!is.null(julia_path_arg)) {
  if (!file.exists(julia_path_arg)) stop("--julia path does not exist: ", julia_path_arg)
  julia_text <- readLines(julia_path_arg, warn = FALSE)
  julia_source_desc <- paste0("file: ", julia_path_arg)
} else {
  out <- suppressWarnings(system2(
    "git", c("-C", shQuote(julia_repo), "show", paste0(ref, ":docs/design/capability-status.md")),
    stdout = TRUE, stderr = TRUE
  ))
  status <- attr(out, "status")
  if (is.null(status)) status <- 0L
  if (status == 0L && length(out) > 0) {
    julia_text <- out
    julia_source_desc <- paste0("git -C \"", julia_repo, "\" show ", ref, ":docs/design/capability-status.md")
  } else {
    if (!file.exists(SCRATCHPAD_FALLBACK)) {
      stop("git show failed against ", julia_repo, " @ ", ref,
           " AND the scratchpad fallback is missing: ", SCRATCHPAD_FALLBACK)
    }
    julia_text <- readLines(SCRATCHPAD_FALLBACK, warn = FALSE)
    julia_source_desc <- paste0("FALLBACK (git show against \"", julia_repo, "\" @ ", ref,
                                 " failed) -> scratchpad copy: ", SCRATCHPAD_FALLBACK)
  }
}

if (!file.exists(R_LEDGER_PATH)) {
  stop("R ledger not found at ", R_LEDGER_PATH,
       " -- run dev/gapclose/build-capability-status.R first")
}
r_text <- readLines(R_LEDGER_PATH, warn = FALSE)

# ---------------------------------------------------------------------------
# 2. Parsers. Both files are pipe-tables under "## " headings. We only parse
#    tables whose header row is literally "| Capability | Status | ..." --
#    this deliberately EXCLUDES GLLVM.jl's two comparator tables ("surface |
#    R mirror | engine | engine-only" and "family / link | log-det curvature
#    | note"), which are prose evidence, not capability rows (per the B2
#    brief: "the prose... sections are context, not rows"). If a status cell
#    inside a real Capability|Status table ever carries a non-canonical word
#    (Julia's own "**observed**" / "Fisher" markers, seen elsewhere in that
#    file's curvature-census table but never inside a Capability|Status
#    table), normalize_status() below treats it as `implemented` with an
#    "(observed)" note, per the B2 brief.
# ---------------------------------------------------------------------------

strip_md <- function(x) {
  x <- gsub("\\*\\*", "", x)
  trimws(x)
}

normalize_status <- function(raw) {
  raw <- strip_md(raw)
  # first token/word run at the start of the cell
  m <- regmatches(raw, regexec("^([A-Za-z][A-Za-z-]*)", raw))[[1]]
  word <- if (length(m) >= 2) tolower(m[2]) else tolower(raw)
  canonical <- c("implemented", "planned", "missing", "rejected")
  if (word %in% canonical) {
    list(word = word, note = if (nchar(raw) > nchar(word)) trimws(sub(paste0("^", word), "", raw, ignore.case = TRUE)) else "")
  } else {
    list(word = "implemented", note = paste0("(non-canonical status cell '", raw, "' normalized to implemented/observed per B2 brief)"))
  }
}

# Parse a markdown file into: for each "## <group>" section, each pipe-table
# whose header row's first two non-empty cells are "Capability" and "Status".
parse_capability_tables <- function(lines) {
  rows <- list()
  cur_group <- NA_character_
  in_target_table <- FALSE
  n <- length(lines)
  i <- 1
  while (i <= n) {
    ln <- lines[i]
    if (grepl("^##+\\s+", ln)) {
      cur_group <- trimws(sub("^##+\\s+", "", ln))
      in_target_table <- FALSE
      i <- i + 1
      next
    }
    if (grepl("^\\|", ln)) {
      cells <- strsplit(ln, "\\|")[[1]]
      cells <- trimws(cells)
      cells <- cells[cells != "" | seq_along(cells) != 1]  # drop leading empty from split
      cells <- cells[nzchar(cells) | seq_along(cells) > 0]
      # re-split properly: markdown row "| a | b | c |" -> strsplit gives c("", " a ", " b ", " c ")
      raw_cells <- strsplit(ln, "\\|")[[1]]
      if (length(raw_cells) >= 2) raw_cells <- raw_cells[-1]
      if (length(raw_cells) >= 1 && trimws(raw_cells[length(raw_cells)]) == "") {
        raw_cells <- raw_cells[-length(raw_cells)]
      }
      raw_cells <- trimws(raw_cells)
      if (length(raw_cells) >= 2 && tolower(raw_cells[1]) == "capability" && tolower(raw_cells[2]) == "status") {
        in_target_table <- TRUE
        i <- i + 1
        next
      }
      if (grepl("^-{2,}\\s*$", raw_cells[1] %||% "")) { i <- i + 1; next }  # separator row "|---|---|"
      if (in_target_table && length(raw_cells) >= 2 && !grepl("^-+$", gsub("[: ]", "", raw_cells[1]))) {
        name <- raw_cells[1]
        st_raw <- raw_cells[2]
        aliases_raw <- if (length(raw_cells) >= 3) raw_cells[3] else ""
        reg_rows_raw <- if (length(raw_cells) >= 4) raw_cells[4] else ""
        note_raw <- if (length(raw_cells) >= 5) raw_cells[5] else ""
        st <- normalize_status(st_raw)
        rows[[length(rows) + 1]] <- list(
          group = cur_group, name = name, status = st$word, status_note = st$note,
          status_raw = st_raw, aliases = aliases_raw, register_rows = reg_rows_raw, note = note_raw
        )
      } else if (!grepl("^-+$", gsub("[: ]", "", raw_cells[1] %||% "-"))) {
        in_target_table <- FALSE
      }
    } else {
      in_target_table <- FALSE
    }
    i <- i + 1
  }
  rows
}

`%||%` <- function(a, b) if (is.null(a) || length(a) == 0) b else a

julia_rows <- parse_capability_tables(julia_text)
r_rows <- parse_capability_tables(r_text)

if (length(julia_rows) == 0) stop("parsed 0 capability rows from the Julia ledger -- check the source/parser")
if (length(r_rows) == 0) stop("parsed 0 capability rows from the R ledger -- run the B1 generator first")

# ---------------------------------------------------------------------------
# 3. Name normalization + join.
# ---------------------------------------------------------------------------

norm_name <- function(x) {
  x <- gsub("`", "", x)
  x <- gsub("\\s+", " ", x)
  trimws(tolower(x))
}
ultra_norm <- function(x) {
  x <- tolower(x)
  gsub("[^a-z0-9]", "", x)
}

split_aliases <- function(x) {
  if (!nzchar(x)) return(character(0))
  trimws(strsplit(x, ";")[[1]])
}

# R key table: normalized name/alias -> index into r_rows
r_keys <- new.env()
for (idx in seq_along(r_rows)) {
  keys <- c(r_rows[[idx]]$name, split_aliases(r_rows[[idx]]$aliases))
  for (k in keys) assign(norm_name(k), idx, envir = r_keys)
}

matched <- list()      # list(julia_idx, r_idx)
julia_only_idx <- integer(0)
for (j in seq_along(julia_rows)) {
  key <- norm_name(julia_rows[[j]]$name)
  if (exists(key, envir = r_keys, inherits = FALSE)) {
    matched[[length(matched) + 1]] <- list(julia_idx = j, r_idx = get(key, envir = r_keys))
  } else {
    julia_only_idx <- c(julia_only_idx, j)
  }
}
r_matched_idx <- unique(vapply(matched, `[[`, integer(1), "r_idx"))
r_only_idx <- setdiff(seq_along(r_rows), r_matched_idx)

# ---------------------------------------------------------------------------
# 4. Divergence notes on MATCHED rows -- the collision list where BOTH sides
#    have a same-named row but the underlying semantics genuinely differ
#    (not a false join -- a true parity caveat).
# ---------------------------------------------------------------------------

NOTED_DIVERGENCES <- list(
  list(pattern = "^student$",
       reason = "Student-t nu: GLLVM.jl's parity Delta is paid only with nu FIXED on both sides; gllvmTMB's default `student()` ESTIMATES nu per trait -- the two `implemented` statuses are not the same claim."),
  list(pattern = "^kernel",
       reason = "kernel PSD-vs-PD: R's kernel_* keyword family documents a PSD requirement on the supplied K; GLLVM.jl's dense-kernel fitter's positive-definiteness contract has not been cross-checked against that requirement -- treat a status match here as unverified equivalence, not confirmed parity."),
  list(pattern = "^aghq estimator$",
       reason = "AGHQ shape: gllvmTMB's `aghq` is a public opt-in knob (`gllvmTMBcontrol(aghq = ...)`); GLLVM.jl's own AGHQ-shaped kernel (src/families/aghq_grid.jl) is internal-only, unreceipted as a public capability, and its own ledger keeps 'AGHQ estimator' at `missing` -- a genuine status disagreement, not merely a naming collision.")
)

divergence_note_for <- function(name) {
  n <- norm_name(name)
  for (d in NOTED_DIVERGENCES) if (grepl(d$pattern, n)) return(d$reason)
  ""
}

# ---------------------------------------------------------------------------
# 5. Disposition table for Julia-only rows: port (genuinely owed to R) /
#    accounted (engine-internal or already-explained, not owed) / divergence
#    (a real semantic gap under a shared-sounding name). Keyed by normalized
#    Julia row name; a few are also matched by substring for names we expect
#    might appear only in prose (never as a parsed row given the
#    Capability|Status table filter) -- those entries are written for
#    completeness per the B2 brief and are inert (never fire) unless a future
#    edit to the Julia ledger turns them into a real table row.
# ---------------------------------------------------------------------------

PORT <- list(
  "zip / zinb / zib" = "zero-inflated Poisson/NB/Binomial trio: gllvmTMB cut ZIP/ZINB/ZIB; genuinely owed if the maintainer wants them back",
  "ordinal_probit / cumulative_logit" = "logit-link cumulative ordinal response: gllvmTMB only ships ordinal_probit (FAM-14); the logit-link variant is a genuine port target",
  "censored_poisson" = "right-censored Poisson response family: gllvmTMB has no censored_poisson constructor at all (FAM-16 tracks only truncated_nbinom1); genuinely owed",
  "fourth-corner / trait–environment" = "fourth-corner / trait-environment estimand: no dedicated register row found; genuinely owed",
  "concurrent / constrained / rrr ordination (num.lv.c / num.rr)" = "constrained/concurrent RRR ordination (num.lv.c / num.RR): no register row found; genuinely owed",
  "quadratic response" = "quadratic (unimodal) response-curve ordination axis: no register row found; genuinely owed",
  # given by the brief as concepts, not confirmed as parseable rows in the
  # Julia ledger read for this build; kept for completeness, inert if unused
  "select_lv" = "select_lv-style latent-dimension selection helper: not confirmed as a live Julia ledger row at build time; genuinely owed if/when it appears",
  "boundary lrt/anova" = "boundary-aware LRT/anova comparison: not confirmed as a live Julia ledger row at build time; genuinely owed if/when it appears",
  "ordination_uncertainty" = "ordination_uncertainty helper: not confirmed as a live Julia ledger row at build time; genuinely owed if/when it appears"
)

ACCOUNTED <- list(
  # Grounded in the Julia file's own prose (## Covariance structure grid notes,
  # "Julia phylo rows share three equivalent likelihood representations
  # (sparse CHOLMOD, contrasts, edge-incidence)") -- engine-internal
  # representation detail, not a distinct capability row; these strings are
  # never parsed as Capability|Status rows by this tool's table-header
  # filter, so this entry is inert unless the Julia ledger promotes it to a
  # real row.
  "felsenstein contrasts" = "engine-internal phylo likelihood representation (one of three equivalent forms: sparse CHOLMOD / contrasts / edge-incidence); prose evidence in GLLVM.jl's ledger, not a capability row",
  "edge-incidence" = "engine-internal phylo likelihood representation, same prose note as Felsenstein contrasts above",
  # UNVERIFIED (AGENT-INFERRED): not located as an exact row or prose
  # sentence in the read of the Julia ledger for this build; included per
  # the B2 brief's disposition list regardless, and flagged UNVERIFIED in
  # dev/gapclose/B-parity-notes.md. Inert unless/until confirmed.
  "relaxed clock" = "UNVERIFIED: phylogenetic relaxed-clock engine internals, not located as an exact row in this build's read of the Julia ledger; included per the B2 brief, treated as engine-internal if it appears",
  "node-frame gradient" = "UNVERIFIED: sparse phylo gradient engine internals, not located as an exact row in this build's read of the Julia ledger; included per the B2 brief",
  "takahashi" = "UNVERIFIED: Takahashi selected-inverse sparse linear algebra (cf. the identical DRM.jl precedent entry); not located as an exact row in this build's read of the Julia ledger",
  "em family" = "UNVERIFIED: EM-style estimator engine internals, not located as an exact row in this build's read of the Julia ledger",
  "ppca init" = "UNVERIFIED: probabilistic-PCA starting-value engine internals, not located as an exact row in this build's read of the Julia ledger",
  # Grounded: the Julia file's own "## Laplace curvature" section is a
  # `family / link | log-det curvature | note` table, a different header
  # from `Capability | Status` -- this tool's table filter deliberately
  # excludes it, so it never surfaces as a row needing disposition. Recorded
  # here for documentation completeness per the B2 brief.
  "laplace curvature contract" = "the family/link log-det curvature census uses a different table header (`family / link | log-det curvature | note`), not `Capability | Status`; excluded from row-level parsing by design (see this script's parser comment), tracked as an engine-internal precision detail, not a capability row",

  # --- Discovered running this tool against the live GLLVM.jl repo ---------
  # Julia's own R<->Julia parity-testing infrastructure, not an R capability.
  "light gllvmtmb loglik named routes (63/63)" = "GLLVM.jl's own internal R<->Julia parity-testing scaffold (light RCall Delta checks); not a capability of gllvmTMB to mirror",
  "shared-x light loglik gauss/bin/pois (18/18)" = "same as the named-routes row above: Julia's own parity-testing infrastructure, not an R capability",
  # Granularity: R has the capability but under a different, already-matched
  # ledger row name (folded into a coarser row above rather than duplicated).
  "species-specific environmental coefficients" = "structurally the same mechanism as the matched 'Fixed-effect covariates X' row (FG-02: (0+trait):x per-species slopes); not tracked as a separate register row",
  "row effects fixed" = "ordinary fixed-effect design terms, covered by the matched 'Fixed-effect covariates X' / 'grouping level x unit' rows; not tracked as a separate register row",
  "row effects random" = "covered by the matched 'grouping level x unit_obs' row (RE-01/RE-06 ordinary and OLRE random intercepts); not tracked as a separate register row",
  "per-species / grouped dispersion (disp.group)" = "gllvmTMB's per-trait dispersion (FAM-05/07/08/09/10) is default engine behaviour, not a separately named register row",
  "@formula / long+wide data (fixed effects)" = "covered by the matched 'grouping level x unit' row (FG-01/02/03 long/wide constructors); naming difference only",
  # R HAS these; the Julia row is `planned` (R is ahead here) but the R
  # ledger folds the evidence into a differently-named row (RE-02/RE-03
  # inside "grouping level x unit"), so the name-based join misses it.
  "keyworded random slopes (≥1)" = "R already has this (RE-01/RE-02, folded into the matched 'grouping level x unit' row above, both `covered`); a naming/granularity difference, not a gap owed to R -- if anything Julia is behind here",
  "uncorrelated slope (r double-bar / uncorrelated re)" = "no register evidence for a distinct `||` uncorrelated-slope grammar on either side; both packages lack it, so this is not a Julia-ahead gap",
  # Bridge: R's register (JUL-01 / JUL-01A, matched above as the two
  # coarser 'Julia bridge ...' rows) already carries this same admitted,
  # partial-vs-full-parity bridge surface; GLLVM.jl's ledger just splits it
  # into ten finer sub-rows this generator does not mirror 1:1.
  "bridge capability ledger + drift probe (**probe is red — see fence below**)" = "granularity difference: covered by the matched JUL-01A row ('Julia bridge unit-tier covariance and ordination accessors') above",
  "bridge no-x point fit (core one-part families)" = "granularity difference: covered by the matched JUL-01 row ('Lean engine=julia reduced-rank bridge') above",
  "bridge fixed-effect x (selected families)" = "granularity difference: covered by the matched JUL-01 row above",
  "bridge missing-response mask (selected families)" = "granularity difference: covered by the matched JUL-01 row above",
  "bridge ci transport wald/profile/bootstrap (selected)" = "granularity difference: covered by the matched JUL-01 row above",
  "bridge predictor-informed lv / x_lv (selected)" = "granularity difference: covered by the matched JUL-01 row above (JUL-01/01A predictor-informed latent-score addendum)",
  "bridge mixed-family vector" = "granularity difference: covered by the matched JUL-01 row above",
  "bridge full family × full structure parity" = "both sides refuse this claim by decision -- R's JUL-01/01A rows are explicitly 'partial vs full R-user parity' with no full-parity claim either",
  "bridge phylo / animal / spatial / kernel source parity" = "not yet built on either side; R's structured-source bridge rows (JUL-01/01A) do not cover phylo/animal/spatial/kernel either",
  "bridge phylo model a / source-specific lv advertising" = "matches R's own LV-08 fence (already matched to the 'phylo_latent + lv = ~ x (Phylo Model A)' row above): both sides withhold this advertising claim by decision",
  "full family r↔julia parity claim" = "matches the register's own Honest scope statement (docs/design/35-validation-debt-register.md): gllvmTMB makes no full-family-parity claim either; both sides refuse the same claim by decision",
  "phylo model a public interval promotion" = "duplicate framing of the same LV-08 fence matched to the 'phylo_latent + lv = ~ x (Phylo Model A)' row above -- both sides withhold this promotion",
  "delta/hurdle latent-scale correlation advertising" = "matches R's MIX-10 (mixed-family delta/hurdle latent-scale correlation, `partial`, route-only): both sides fence this advertising claim",
  "non-gaussian reml" = "matches R's own MIS-33 fence (Gaussian-only REML; non-Gaussian REML is not built): both sides refuse this by decision",
  "broad aghq (julia)" = "duplicate of the already-matched 'AGHQ estimator' row (see its NOTED_DIVERGENCES note above) -- GLLVM.jl's ledger lists AGHQ twice (main table + Withdrawn table); this tool joins the first occurrence"
)

DIVERGENCE <- list(
  "student-t nu" = "gllvmTMB estimates nu per trait by default; GLLVM.jl's parity Delta is paid only at fixed nu -- see NOTED_DIVERGENCES on the matched `student` row",
  "kernel psd-vs-pd" = "R's kernel_* keywords document a PSD requirement; GLLVM.jl's PD contract for the same dense-kernel fitter is unverified against it -- see NOTED_DIVERGENCES on the matched kernel rows",
  "aghq shape" = "R's aghq is a public opt-in knob; GLLVM.jl's internal AGHQ-shaped kernel is unreceipted as a public capability and stays `missing` on its own ledger -- see NOTED_DIVERGENCES on the matched `AGHQ estimator` row"
)

disposition_for <- function(name) {
  n <- norm_name(name)
  if (!is.null(PORT[[n]])) return(list(type = "port", reason = PORT[[n]]))
  if (!is.null(ACCOUNTED[[n]])) return(list(type = "accounted", reason = ACCOUNTED[[n]]))
  if (!is.null(DIVERGENCE[[n]])) return(list(type = "divergence", reason = DIVERGENCE[[n]]))
  # substring fallback for the prose-only / possibly-renamed concepts
  for (nm in names(PORT)) if (grepl(nm, n, fixed = TRUE) || grepl(n, nm, fixed = TRUE)) return(list(type = "port", reason = PORT[[nm]]))
  for (nm in names(ACCOUNTED)) if (grepl(nm, n, fixed = TRUE)) return(list(type = "accounted", reason = ACCOUNTED[[nm]]))
  for (nm in names(DIVERGENCE)) if (grepl(nm, n, fixed = TRUE)) return(list(type = "divergence", reason = DIVERGENCE[[nm]]))
  NULL
}

# ---------------------------------------------------------------------------
# 6. --check-names: near-miss detection (case/space/punctuation-insensitive
#    match that is NOT an exact norm_name() match -- almost always a real
#    formatting bug, since a genuine concept difference should not hinge on
#    case/spacing) + the four required grouping-level rows.
# ---------------------------------------------------------------------------

r_ultra <- setNames(vapply(r_rows, function(r) ultra_norm(r$name), character(1)), NULL)
julia_ultra <- setNames(vapply(julia_rows, function(r) ultra_norm(r$name), character(1)), NULL)

near_misses <- character(0)
for (j in julia_only_idx) {
  ju <- ultra_norm(julia_rows[[j]]$name)
  hit <- which(r_ultra == ju)
  if (length(hit) > 0) {
    near_misses <- c(near_misses, sprintf("Julia %-60s <-> R %s",
                                           shQuote(julia_rows[[j]]$name), shQuote(r_rows[[hit[1]]]$name)))
  }
}
for (ri in r_only_idx) {
  ru <- ultra_norm(r_rows[[ri]]$name)
  hit <- which(julia_ultra == ru)
  if (length(hit) > 0) {
    near_misses <- c(near_misses, sprintf("R %-60s <-> Julia %s",
                                           shQuote(r_rows[[ri]]$name), shQuote(julia_rows[[hit[1]]]$name)))
  }
}
near_misses <- unique(near_misses)

REQUIRED_GROUPING_ROWS <- c("grouping level × unit", "grouping level × unit_obs",
                             "grouping level × cluster", "grouping level × cluster2")
r_names_norm <- vapply(r_rows, function(r) norm_name(r$name), character(1))
missing_grouping <- REQUIRED_GROUPING_ROWS[!norm_name(REQUIRED_GROUPING_ROWS) %in% r_names_norm]

# ---------------------------------------------------------------------------
# 7. Collision guard: named collision rows must never join to the WRONG
#    Julia row (verified structurally, not just printed).
# ---------------------------------------------------------------------------

collision_failures <- character(0)
cum_logit_r <- r_rows[[which(r_names_norm == norm_name("cumulative_logit (missing-predictor family)"))[1]]]
if (!is.null(cum_logit_r)) {
  key <- norm_name(cum_logit_r$name)
  if (exists(key, envir = r_keys, inherits = FALSE)) {
    idx <- get(key, envir = r_keys)
    if (!identical(idx, which(r_names_norm == key)[1])) collision_failures <- c(collision_failures, "cumulative_logit key routes to the wrong R row index")
  }
  matched_julia <- Filter(function(m) m$r_idx == which(r_names_norm == key)[1], matched)
  if (length(matched_julia) > 0) {
    for (mm in matched_julia) {
      jname <- norm_name(julia_rows[[mm$julia_idx]]$name)
      if (grepl("ordinal", jname)) {
        collision_failures <- c(collision_failures,
          sprintf("cumulative_logit (missing-predictor family) incorrectly joined to Julia row '%s'", julia_rows[[mm$julia_idx]]$name))
      }
    }
  }
}

# ---------------------------------------------------------------------------
# 8. Report.
# ---------------------------------------------------------------------------

cat(sprintf("R ledger:     %s (%d rows)\n", R_LEDGER_PATH, length(r_rows)))
cat(sprintf("Julia ledger: %s (%d rows)\n", julia_source_desc, length(julia_rows)))
cat("\n")

cat(sprintf("COUNTS: %d matched, %d R-only, %d Julia-only\n",
            length(matched), length(r_only_idx), length(julia_only_idx)))
cat("\n")

cat(sprintf("MATCHED ROWS (%d)\n", length(matched)))
for (m in matched) {
  jr <- julia_rows[[m$julia_idx]]; rr <- r_rows[[m$r_idx]]
  agree <- identical(
    sub(" .*$", "", jr$status),
    sub(" .*$", "", rr$status)
  )
  # `implemented` on both sides still agrees; anything else needing nuance
  # (e.g. R `scope-limited` vs Julia `implemented`) is flagged.
  flag <- if (jr$status == rr$status) "AGREE" else if (jr$status == "implemented" && rr$status %in% c("scope-limited", "point-fit-recovery")) "R-NARROWER" else if (rr$status == "implemented" && jr$status != "implemented") "R-AHEAD" else "DIFFER"
  dv <- divergence_note_for(rr$name)
  cat(sprintf("  [%-11s] %-70s R=%-20s Julia=%s%s\n",
              flag, rr$name, rr$status, jr$status,
              if (nzchar(dv)) paste0("\n      divergence: ", dv) else ""))
}
cat("\n")

cat(sprintf("AHEAD OF gllvmTMB, ACCOUNTED FOR IN WRITING -- Julia-only rows with a disposition (%d)\n", length(julia_only_idx)))
undispositioned <- character(0)
for (j in julia_only_idx) {
  jr <- julia_rows[[j]]
  d <- disposition_for(jr$name)
  if (is.null(d)) {
    undispositioned <- c(undispositioned, jr$name)
    cat(sprintf("  [UNDISPOSITIONED] %s (status=%s)\n", jr$name, jr$status))
  } else {
    cat(sprintf("  [%-10s] %-60s %s\n", toupper(d$type), jr$name, d$reason))
  }
}
cat("\n")

cat(sprintf("AHEAD OF GLLVM.jl -- R-only rows (%d), for symmetry\n", length(r_only_idx)))
for (ri in r_only_idx) {
  rr <- r_rows[[ri]]
  cat(sprintf("  %-70s R status=%s\n", rr$name, rr$status))
}
cat("\n")

if (CHECK_NAMES) {
  cat("--check-names\n")
  if (length(near_misses) == 0) {
    cat("0 near-miss\n")
  } else {
    cat(sprintf("%d near-miss(es) -- likely formatting bugs, not real divergences:\n", length(near_misses)))
    for (nm in near_misses) cat("  ", nm, "\n")
  }
  if (length(missing_grouping) == 0) {
    cat("all 4 grouping-level rows present (unit / unit_obs / cluster / cluster2)\n")
  } else {
    cat("MISSING grouping-level rows: ", paste(missing_grouping, collapse = ", "), "\n")
  }
  cat("\n")
}

closure_ok <- length(undispositioned) == 0 && length(near_misses) == 0 &&
  length(missing_grouping) == 0 && length(collision_failures) == 0

if (closure_ok) {
  cat(sprintf("CLOSURE: PASS -- every one of %d Julia-only rows carries a port/accounted/divergence disposition, 0 near-misses, all 4 grouping-level rows present, collision rows join correctly\n",
              length(julia_only_idx)))
} else {
  cat("CLOSURE: FAIL\n")
  if (length(undispositioned) > 0) cat(sprintf("  %d Julia-only row(s) have no disposition: %s\n", length(undispositioned), paste(undispositioned, collapse = "; ")))
  if (length(near_misses) > 0) cat(sprintf("  %d near-miss name(s)\n", length(near_misses)))
  if (length(missing_grouping) > 0) cat(sprintf("  missing grouping-level rows: %s\n", paste(missing_grouping, collapse = ", ")))
  if (length(collision_failures) > 0) cat(sprintf("  collision failures: %s\n", paste(collision_failures, collapse = "; ")))
}

quit(status = if (closure_ok) 0L else 1L, save = "no")
