suppressMessages(library(gllvm))
set.seed(1)
n <- 30; p <- 6; q <- 1
Lt <- matrix(rnorm(p * q, 0, 0.6), p, q)
u  <- matrix(rnorm(n * q), n, q)
b  <- rnorm(p, 0.3, 0.3)
eta <- sweep(u %*% t(Lt), 2, b, "+")
Y <- matrix(rbinom(n * p, 1, plogis(eta)), n, p)
colnames(Y) <- paste0("sp", seq_len(p))
fit <- gllvm(y = Y, family = binomial(), num.lv = q, method = "EVA", seed = 1)
cat("names(fit):\n"); print(names(fit))
cat("\nclass(fit$convergence):", class(fit$convergence), " value:", fit$convergence, "\n")
cat("names(fit$params):\n"); print(names(fit$params))
cat("\ndim(fit$params$theta):", dim(as.matrix(fit$params$theta)), "\n")
cat("fit$params$sigma.lv:", fit$params$sigma.lv, "\n")
cat("length(fit$params$beta0):", length(fit$params$beta0), "\n")
cat("\nfit$logL:", fit$logL, "\n")
cat("fit$method:", fit$method, "\n")
cat("fit$family:", fit$family, "\n")
cat("fit$link (if present):", if("link" %in% names(fit)) fit$link else "ABSENT", "\n")
cat("\nnames(fit$TMBfn) present?", "TMBfn" %in% names(fit), "\n")
if (!is.null(fit$sd)) cat("fit$sd present\n")
str(fit[c("convergence")], max.level=1)
## check for a Hessian / PD flag
grep_names <- grep("hess|Hess|sd|opt", names(fit), value = TRUE, ignore.case=TRUE)
print(grep_names)
